/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Incident } from '../types/security';

export function getInitialSampleIncidents(): Incident[] {
  const now = Date.now();

  return [
    {
      incident_id: 'INC-8021',
      title: 'Multi-stage SQL Injection & Data Exfiltration on dmz-ecommerce-web',
      created_at: new Date(now - 35 * 60 * 1000).toISOString(),
      updated_at: new Date(now - 8 * 60 * 1000).toISOString(),
      severity: 'CRITICAL',
      status: 'Investigating',
      threat_category: 'SQL Injection Attempt',
      assigned_to: 'Alex Morgan (Tier 3)',
      detection_origin: 'RULE_AND_AI',
      event_ids: ['EVT-WEB-500', 'EVT-WEB-501', 'EVT-WEB-502', 'EVT-WEB-510', 'EVT-OUT-601'],
      target_assets: ['dmz-ecommerce-web'],
      threat_actors_ips: ['203.0.113.88', '198.51.100.200'],
      summary:
        'External IP 203.0.113.88 launched automated SQL injection payloads against dmz-ecommerce-web. Suricata IDS alerted on UNION SELECT signature, followed by an anomalous 18.4MB outbound session to external staging IP 198.51.100.200:8443.',
      mitre_tactics: ['Initial Access (T1190)', 'Credential Access (T1003)', 'Command and Control (T1071)', 'Exfiltration (T1041)'],
      containment_checklist: [
        { id: 'c1', title: 'Block threat IP 203.0.113.88 at perimeter firewall', completed: true, completed_by: 'Alex Morgan' },
        { id: 'c2', title: 'Block egress to exfiltration endpoint 198.51.100.200:8443', completed: true, completed_by: 'Alex Morgan' },
        { id: 'c3', title: 'Isolate host dmz-ecommerce-web to quarantine VLAN', completed: false },
        { id: 'c4', title: 'Extract web server access logs and database audit records', completed: false },
        { id: 'c5', title: 'Rotate database connection pool credentials and patch URI endpoints', completed: false },
      ],
      analyst_notes: [
        {
          id: 'n1',
          author: 'Alex Morgan (Tier 3)',
          timestamp: new Date(now - 30 * 60 * 1000).toISOString(),
          note: 'Rule RULE-05-SUSPICIOUS-WEB triggered on UNION SELECT probe. Correlation confirmed matching Suricata SID 2018402.',
        },
        {
          id: 'n2',
          author: 'Sarah Chen (SOC Lead)',
          timestamp: new Date(now - 14 * 60 * 1000).toISOString(),
          note: 'NetFlow exfiltration session verified: 18.4MB transmitted to external IP. Ingress block active.',
        },
      ],
      attack_timeline: [
        {
          id: 'tl-8021-1',
          timestamp: new Date(now - 34 * 60 * 1000).toISOString(),
          time_display: new Date(now - 34 * 60 * 1000).toTimeString().split(' ')[0],
          action: 'SQL injection probe received',
          description: "WAF SQLi match: UNION SELECT query injection in URI parameters (/products?cat=1')",
          source_ip: '203.0.113.88',
          destination_ip: '10.0.1.50',
          asset: 'dmz-ecommerce-web',
          severity: 'HIGH',
          event_id: 'EVT-WEB-500',
        },
        {
          id: 'tl-8021-2',
          timestamp: new Date(now - 33 * 60 * 1000).toISOString(),
          time_display: new Date(now - 33 * 60 * 1000).toTimeString().split(' ')[0],
          action: 'Authentication bypass attempt',
          description: "WAF SQLi match: Boolean tautology authentication bypass (' OR '1'='1')",
          source_ip: '203.0.113.88',
          destination_ip: '10.0.1.50',
          asset: 'dmz-ecommerce-web',
          severity: 'HIGH',
          event_id: 'EVT-WEB-501',
        },
        {
          id: 'tl-8021-3',
          timestamp: new Date(now - 32 * 60 * 1000).toISOString(),
          time_display: new Date(now - 32 * 60 * 1000).toTimeString().split(' ')[0],
          action: 'IDS intrusion signature triggered',
          description: 'ET WEB_SPECIFIC_APPS SQL Injection Union Select keyword detected by Suricata',
          source_ip: '203.0.113.88',
          destination_ip: '10.0.1.50',
          asset: 'dmz-ecommerce-web',
          severity: 'CRITICAL',
          event_id: 'EVT-WEB-510',
        },
        {
          id: 'tl-8021-4',
          timestamp: new Date(now - 30 * 60 * 1000).toISOString(),
          time_display: new Date(now - 30 * 60 * 1000).toTimeString().split(' ')[0],
          action: 'Internal resource accessed & exfiltration initiated',
          description: 'Persistent outbound TCP session established to external IP 198.51.100.200:8443 (Volume: 18.4MB)',
          source_ip: '10.0.4.82',
          destination_ip: '198.51.100.200',
          asset: 'workstation-fin-09',
          severity: 'CRITICAL',
          event_id: 'EVT-OUT-601',
        },
      ],
    },
    {
      incident_id: 'INC-8022',
      title: 'Credential Guessing to Breakthrough Compromise & Root Escalation',
      created_at: new Date(now - 25 * 60 * 1000).toISOString(),
      updated_at: new Date(now - 5 * 60 * 1000).toISOString(),
      severity: 'CRITICAL',
      status: 'Investigating',
      threat_category: 'Suspicious Authentication',
      assigned_to: 'Sarah Chen (SOC Lead)',
      detection_origin: 'RULE',
      event_ids: ['EVT-SEQ-201', 'EVT-SEQ-202', 'EVT-SEQ-203', 'EVT-SEQ-204', 'EVT-SEQ-205', 'EVT-PRIV-701'],
      target_assets: ['corp-vpn-gw', 'jump-bastion-01'],
      threat_actors_ips: ['185.220.101.44'],
      summary:
        'Credential brute-force attack from 185.220.101.44 against RADIUS VPN endpoint. After 3 consecutive failed challenges, account svc_jenkins_ci logged in successfully, established an SSL VPN tunnel, and elevated to root UID via sudo su -.',
      mitre_tactics: ['Credential Access (T1110)', 'Initial Access (T1078)', 'Privilege Escalation (T1548)'],
      containment_checklist: [
        { id: 'b1', title: 'Terminate active SSL VPN tunnel assigned to svc_jenkins_ci', completed: true, completed_by: 'Sarah Chen' },
        { id: 'b2', title: 'Revoke and reset LDAP password and API tokens for svc_jenkins_ci', completed: true, completed_by: 'Sarah Chen' },
        { id: 'b3', title: 'Block threat IP 185.220.101.44 at perimeter firewall', completed: true, completed_by: 'Sarah Chen' },
        { id: 'b4', title: 'Audit jump-bastion-01 root command history and cron tab persistence', completed: false },
      ],
      analyst_notes: [
        {
          id: 'nb1',
          author: 'Sarah Chen (SOC Lead)',
          timestamp: new Date(now - 22 * 60 * 1000).toISOString(),
          note: 'Rule RULE-03-SUSPICIOUS-AUTH fired with 94% confidence. Compromised credential validated across jump host.',
        },
      ],
      attack_timeline: [
        {
          id: 'tl-8022-1',
          timestamp: new Date(now - 24 * 60 * 1000).toISOString(),
          time_display: new Date(now - 24 * 60 * 1000).toTimeString().split(' ')[0],
          action: 'Failed authentication',
          description: 'Failed password challenge for account svc_jenkins_ci from 185.220.101.44 (attempt #1)',
          source_ip: '185.220.101.44',
          destination_ip: '10.0.1.5',
          asset: 'corp-vpn-gw',
          username: 'svc_jenkins_ci',
          severity: 'MEDIUM',
          event_id: 'EVT-SEQ-201',
        },
        {
          id: 'tl-8022-2',
          timestamp: new Date(now - 23 * 60 * 1000).toISOString(),
          time_display: new Date(now - 23 * 60 * 1000).toTimeString().split(' ')[0],
          action: 'Failed authentication',
          description: 'Failed password challenge for account svc_jenkins_ci from 185.220.101.44 (attempt #2)',
          source_ip: '185.220.101.44',
          destination_ip: '10.0.1.5',
          asset: 'corp-vpn-gw',
          username: 'svc_jenkins_ci',
          severity: 'HIGH',
          event_id: 'EVT-SEQ-202',
        },
        {
          id: 'tl-8022-3',
          timestamp: new Date(now - 22 * 60 * 1000).toISOString(),
          time_display: new Date(now - 22 * 60 * 1000).toTimeString().split(' ')[0],
          action: 'Failed authentication',
          description: 'Failed password challenge for account svc_jenkins_ci from 185.220.101.44 (attempt #3)',
          source_ip: '185.220.101.44',
          destination_ip: '10.0.1.5',
          asset: 'corp-vpn-gw',
          username: 'svc_jenkins_ci',
          severity: 'HIGH',
          event_id: 'EVT-SEQ-203',
        },
        {
          id: 'tl-8022-4',
          timestamp: new Date(now - 21 * 60 * 1000).toISOString(),
          time_display: new Date(now - 21 * 60 * 1000).toTimeString().split(' ')[0],
          action: 'Successful authentication',
          description: 'Successful authentication for svc_jenkins_ci after 3 failed attempts (Compromise Breakthrough)',
          source_ip: '185.220.101.44',
          destination_ip: '10.0.1.5',
          asset: 'corp-vpn-gw',
          username: 'svc_jenkins_ci',
          severity: 'CRITICAL',
          event_id: 'EVT-SEQ-204',
        },
        {
          id: 'tl-8022-5',
          timestamp: new Date(now - 20 * 60 * 1000).toISOString(),
          time_display: new Date(now - 20 * 60 * 1000).toTimeString().split(' ')[0],
          action: 'Internal resource accessed',
          description: 'SSL VPN tunnel established for user svc_jenkins_ci; assigned internal VIP 10.0.50.88',
          source_ip: '185.220.101.44',
          destination_ip: '10.0.1.5',
          asset: 'corp-vpn-gw',
          username: 'svc_jenkins_ci',
          severity: 'HIGH',
          event_id: 'EVT-SEQ-205',
        },
        {
          id: 'tl-8022-6',
          timestamp: new Date(now - 18 * 60 * 1000).toISOString(),
          time_display: new Date(now - 18 * 60 * 1000).toTimeString().split(' ')[0],
          action: 'Privilege escalation executed',
          description: 'sudo su - executed by user svc_deploy: process elevated to root privileges in /bin/bash',
          source_ip: '10.0.1.10',
          destination_ip: '10.0.1.10',
          asset: 'jump-bastion-01',
          username: 'svc_deploy',
          severity: 'CRITICAL',
          event_id: 'EVT-PRIV-701',
        },
      ],
    },
    {
      incident_id: 'INC-8023',
      title: 'Suspicious Outbound C2 Beaconing & Unauthorized Egress Port 4444',
      created_at: new Date(now - 15 * 60 * 1000).toISOString(),
      updated_at: new Date(now - 3 * 60 * 1000).toISOString(),
      severity: 'HIGH',
      status: 'New',
      threat_category: 'Command-and-Control Indicator',
      assigned_to: 'Alex Morgan (Tier 3)',
      detection_origin: 'RULE',
      event_ids: ['EVT-OUT-601', 'EVT-OUT-602'],
      target_assets: ['workstation-fin-09'],
      threat_actors_ips: ['198.51.100.200'],
      summary:
        'Endpoint workstation-fin-09 initiated unauthorized outbound connection attempts to external IP 198.51.100.200 on suspicious listener port 4444. Perimeter firewall successfully triggered automated egress drop rule.',
      mitre_tactics: ['Command and Control (T1071)', 'Execution (T1204)'],
      containment_checklist: [
        { id: 'm1', title: 'Verify firewall egress block for external destination 198.51.100.200:4444', completed: true, completed_by: 'Alex Morgan' },
        { id: 'm2', title: 'Perform host forensic scan on workstation-fin-09 for Meterpreter / Cobalt Strike stagers', completed: false },
        { id: 'm3', title: 'Review DNS request logs from workstation-fin-09 for domain generation algorithms', completed: false },
      ],
      analyst_notes: [
        {
          id: 'nm1',
          author: 'Alex Morgan (Tier 3)',
          timestamp: new Date(now - 12 * 60 * 1000).toISOString(),
          note: 'Rule RULE-06-SUSPICIOUS-OUTBOUND matched port 4444. Egress dropped.',
        },
      ],
      attack_timeline: [
        {
          id: 'tl-8023-1',
          timestamp: new Date(now - 14 * 60 * 1000).toISOString(),
          time_display: new Date(now - 14 * 60 * 1000).toTimeString().split(' ')[0],
          action: 'Outbound flow established',
          description: 'Persistent outbound TCP session established to 198.51.100.200:8443 (High volume traffic)',
          source_ip: '10.0.4.82',
          destination_ip: '198.51.100.200',
          asset: 'workstation-fin-09',
          username: 'sarah.jenkins',
          severity: 'HIGH',
          event_id: 'EVT-OUT-601',
        },
        {
          id: 'tl-8023-2',
          timestamp: new Date(now - 13 * 60 * 1000).toISOString(),
          time_display: new Date(now - 13 * 60 * 1000).toTimeString().split(' ')[0],
          action: 'Suspicious port connection blocked',
          description: 'Firewall egress block: Unauthorized connection attempt on suspicious port 4444 to 198.51.100.200',
          source_ip: '10.0.4.82',
          destination_ip: '198.51.100.200',
          asset: 'workstation-fin-09',
          username: 'sarah.jenkins',
          severity: 'HIGH',
          event_id: 'EVT-OUT-602',
        },
      ],
    },
    {
      incident_id: 'INC-8024',
      title: 'Distributed SSH Password Spray & Rate-Limit Threshold Violation',
      created_at: new Date(now - 45 * 60 * 1000).toISOString(),
      updated_at: new Date(now - 12 * 60 * 1000).toISOString(),
      severity: 'HIGH',
      status: 'Contained',
      threat_category: 'Brute Force',
      assigned_to: 'Sarah Chen (SOC Lead)',
      detection_origin: 'RULE',
      event_ids: ['EVT-BF-100', 'EVT-BF-101', 'EVT-BF-102', 'EVT-BF-103', 'EVT-BF-104', 'EVT-BF-110'],
      target_assets: ['jump-bastion-01'],
      threat_actors_ips: ['198.51.100.142'],
      summary:
        'Continuous SSH brute force storm originating from external IP 198.51.100.142 targeting system accounts (root, admin, ubuntu, deploy). Edge rate-limiting rule engaged to drop subsequent TCP SYN connections.',
      mitre_tactics: ['Credential Access (T1110)'],
      containment_checklist: [
        { id: 'bf1', title: 'Add permanent IP ban for 198.51.100.142 on perimeter gateway', completed: true, completed_by: 'Sarah Chen' },
        { id: 'bf2', title: 'Verify fail2ban / rate-limiting drop effectiveness on bastion hosts', completed: true, completed_by: 'Sarah Chen' },
      ],
      analyst_notes: [
        {
          id: 'nbf1',
          author: 'Sarah Chen (SOC Lead)',
          timestamp: new Date(now - 40 * 60 * 1000).toISOString(),
          note: 'Threshold of 10 failed logins exceeded. Perimeter rate-limiting engaged automatically.',
        },
      ],
      attack_timeline: [
        {
          id: 'tl-8024-1',
          timestamp: new Date(now - 44 * 60 * 1000).toISOString(),
          time_display: new Date(now - 44 * 60 * 1000).toTimeString().split(' ')[0],
          action: 'Failed authentication',
          description: 'Failed password for invalid user root from 198.51.100.142 (SSH port 22)',
          source_ip: '198.51.100.142',
          destination_ip: '10.0.1.10',
          asset: 'jump-bastion-01',
          username: 'root',
          severity: 'HIGH',
          event_id: 'EVT-BF-100',
        },
        {
          id: 'tl-8024-2',
          timestamp: new Date(now - 43 * 60 * 1000).toISOString(),
          time_display: new Date(now - 43 * 60 * 1000).toTimeString().split(' ')[0],
          action: 'Failed authentication',
          description: 'Failed password for invalid user admin from 198.51.100.142 (SSH port 22)',
          source_ip: '198.51.100.142',
          destination_ip: '10.0.1.10',
          asset: 'jump-bastion-01',
          username: 'admin',
          severity: 'HIGH',
          event_id: 'EVT-BF-101',
        },
        {
          id: 'tl-8024-3',
          timestamp: new Date(now - 42 * 60 * 1000).toISOString(),
          time_display: new Date(now - 42 * 60 * 1000).toTimeString().split(' ')[0],
          action: 'Failed authentication',
          description: 'Failed password for invalid user ubuntu from 198.51.100.142 (SSH port 22)',
          source_ip: '198.51.100.142',
          destination_ip: '10.0.1.10',
          asset: 'jump-bastion-01',
          username: 'ubuntu',
          severity: 'HIGH',
          event_id: 'EVT-BF-102',
        },
        {
          id: 'tl-8024-4',
          timestamp: new Date(now - 41 * 60 * 1000).toISOString(),
          time_display: new Date(now - 41 * 60 * 1000).toTimeString().split(' ')[0],
          action: 'Perimeter rate-limit block applied',
          description: 'Perimeter firewall rate-limiting drop: repeated SSH connection attempts from 198.51.100.142',
          source_ip: '198.51.100.142',
          destination_ip: '10.0.1.10',
          asset: 'jump-bastion-01',
          severity: 'HIGH',
          event_id: 'EVT-BF-110',
        },
      ],
    },
  ];
}
